/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project;

import Class.Film;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import javax.swing.JButton;

/**
 *
 * @author ASUS
 */
public class JadwalPage extends javax.swing.JFrame {

    /**
     * Creates new form DaftarJadwal
     */
    public Film film;
    public String studio;
    public String username;
    LocalDate today = LocalDate.now();

    public JadwalPage(Film film, String studio, String username) {
        initComponents();
        this.film = film;
        this.studio = studio;
        this.username = username;
        tanpilInfo();
        tampilJadwal();
    }

    public void tanpilInfo() {
        namaFilmTxt.setText(film.getNama());
        studioTxt.setText(studio);
        hariIniTxt.setText(today.toString());
        besokTxt.setText(today.plusDays(1).toString());
        lusaTxt.setText(today.plusDays(2).toString());
    }

    private JButton[] daftarBtnSektor(String sektor) {
        JButton[] buttons;

        if (sektor.equals(today.toString())) {
            buttons = new JButton[]{pilih1, pilih2, pilih3, pilih4};
        } else if (sektor.equals(today.plusDays(1).toString())) {
            buttons = new JButton[]{pilih5, pilih6, pilih7, pilih8};
        } else if (sektor.equals(today.plusDays(2).toString())) {
            buttons = new JButton[]{pilih9, pilih10, pilih11, pilih12};
        } else {
            buttons = new JButton[0];
        }
        return buttons;
    }

    public void tutupJadwal() {
        for (int i = 0; i < 3; i++) {
            JButton[] buttons = daftarBtnSektor(today.plusDays(i).toString());
            for (JButton button : buttons) {
                button.setEnabled(false);
            }
        }
    }

    public void tampilJadwal() {
        tutupJadwal();
        String[] jadwalFilmArray = film.getJadwalFilm(film.getNama(), studio);
        for (String jadwalFilm : jadwalFilmArray) {
            if (jadwalFilm != null) {
                String[] jadwal = jadwalFilm.split(" ");
                for (int i = 0; i < 3; i++) {
                    JButton[] buttons = daftarBtnSektor(today.plusDays(i).toString());
                    for (JButton button : buttons) {
                        if (jadwal[0].equals(today.plusDays(i).toString()) && jadwal[1].contains(button.getText())) {
                            button.setEnabled(true);
                        }
                    }
                }
            }
        }
    }

    public void pindahKursi(Film film, String studio, String jadwal, String usernmae) {
        System.out.println(jadwal);
        DaftarKursi daftarKursi = new DaftarKursi(film, studio, jadwal, username);
        daftarKursi.setVisible(true);
        setVisible(false);

        daftarKursi.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                tanpilInfo();
                tampilJadwal();
                setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaFilmTxt = new javax.swing.JLabel();
        studioTxt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        hariIniTxt = new javax.swing.JLabel();
        besokTxt = new javax.swing.JLabel();
        lusaTxt = new javax.swing.JLabel();
        pilih1 = new javax.swing.JButton();
        pilih2 = new javax.swing.JButton();
        pilih3 = new javax.swing.JButton();
        pilih4 = new javax.swing.JButton();
        pilih5 = new javax.swing.JButton();
        pilih6 = new javax.swing.JButton();
        pilih7 = new javax.swing.JButton();
        pilih8 = new javax.swing.JButton();
        pilih9 = new javax.swing.JButton();
        pilih10 = new javax.swing.JButton();
        pilih11 = new javax.swing.JButton();
        pilih12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        namaFilmTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaFilmTxt.setText("Nama Film");

        studioTxt.setText("Nama Studio");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        hariIniTxt.setText("Hari ini");

        besokTxt.setText("Besok");

        lusaTxt.setText("Lusa");

        pilih1.setText("10.30");
        pilih1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih1ActionPerformed(evt);
            }
        });

        pilih2.setText("12.00");
        pilih2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih2ActionPerformed(evt);
            }
        });

        pilih3.setText("13.30");
        pilih3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih3ActionPerformed(evt);
            }
        });

        pilih4.setText("15.00");
        pilih4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih4ActionPerformed(evt);
            }
        });

        pilih5.setText("10.30");
        pilih5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih5ActionPerformed(evt);
            }
        });

        pilih6.setText("12.00");
        pilih6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih6ActionPerformed(evt);
            }
        });

        pilih7.setText("13.30");
        pilih7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih7ActionPerformed(evt);
            }
        });

        pilih8.setText("15.00");
        pilih8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih8ActionPerformed(evt);
            }
        });

        pilih9.setText("10.30");
        pilih9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih9ActionPerformed(evt);
            }
        });

        pilih10.setText("12.00");
        pilih10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih10ActionPerformed(evt);
            }
        });

        pilih11.setText("13.30");
        pilih11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih11ActionPerformed(evt);
            }
        });

        pilih12.setText("15.00");
        pilih12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pilih9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilih10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilih11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilih12))
                    .addComponent(hariIniTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(besokTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pilih1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilih2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilih3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilih4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lusaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pilih5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilih6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilih7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilih8)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(hariIniTxt)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilih1)
                    .addComponent(pilih2)
                    .addComponent(pilih3)
                    .addComponent(pilih4))
                .addGap(21, 21, 21)
                .addComponent(besokTxt)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilih5)
                    .addComponent(pilih6)
                    .addComponent(pilih7)
                    .addComponent(pilih8))
                .addGap(21, 21, 21)
                .addComponent(lusaTxt)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilih9)
                    .addComponent(pilih10)
                    .addComponent(pilih11)
                    .addComponent(pilih12))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaFilmTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(studioTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(namaFilmTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studioTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilih1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih1ActionPerformed
        // TODO add your handling code here:
        pindahKursi(film, studio, hariIniTxt.getText()+" "+pilih1.getText(), username);
    }//GEN-LAST:event_pilih1ActionPerformed

    private void pilih2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih2ActionPerformed
        // TODO add your handling code here:
        pindahKursi(film, studio, hariIniTxt.getText()+" "+pilih2.getText(), username);
    }//GEN-LAST:event_pilih2ActionPerformed

    private void pilih3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih3ActionPerformed
        // TODO add your handling code here:
        pindahKursi(film, studio, hariIniTxt.getText()+" "+pilih3.getText(), username);
    }//GEN-LAST:event_pilih3ActionPerformed

    private void pilih4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih4ActionPerformed
        // TODO add your handling code here:
        pindahKursi(film, studio, hariIniTxt.getText()+" "+pilih4.getText(), username);
    }//GEN-LAST:event_pilih4ActionPerformed

    private void pilih5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih5ActionPerformed
        // TODO add your handling code here:
        pindahKursi(film, studio, besokTxt.getText()+" "+pilih5.getText(), username);
    }//GEN-LAST:event_pilih5ActionPerformed

    private void pilih6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih6ActionPerformed
        // TODO add your handling code here:
        pindahKursi(film, studio, besokTxt.getText()+" "+pilih6.getText(), username);
    }//GEN-LAST:event_pilih6ActionPerformed

    private void pilih7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih7ActionPerformed
        // TODO add your handling code here:
        pindahKursi(film, studio, besokTxt.getText()+" "+pilih7.getText(), username);
    }//GEN-LAST:event_pilih7ActionPerformed

    private void pilih8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih8ActionPerformed
        // TODO add your handling code here:
        pindahKursi(film, studio, besokTxt.getText()+" "+pilih8.getText(), username);
    }//GEN-LAST:event_pilih8ActionPerformed

    private void pilih9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih9ActionPerformed
        // TODO add your handling code here:
        pindahKursi(film, studio, lusaTxt.getText()+" "+pilih9.getText(), username);
    }//GEN-LAST:event_pilih9ActionPerformed

    private void pilih10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih10ActionPerformed
        // TODO add your handling code here:
        pindahKursi(film, studio, lusaTxt.getText()+" "+pilih10.getText(), username);
    }//GEN-LAST:event_pilih10ActionPerformed

    private void pilih11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih11ActionPerformed
        // TODO add your handling code here:
        pindahKursi(film, studio, lusaTxt.getText()+" "+pilih11.getText(), username);
    }//GEN-LAST:event_pilih11ActionPerformed

    private void pilih12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih12ActionPerformed
        // TODO add your handling code here:
        pindahKursi(film, studio, lusaTxt.getText()+" "+pilih12.getText(), username);
    }//GEN-LAST:event_pilih12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JadwalPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JadwalPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JadwalPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JadwalPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel besokTxt;
    private javax.swing.JLabel hariIniTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lusaTxt;
    private javax.swing.JLabel namaFilmTxt;
    private javax.swing.JButton pilih1;
    private javax.swing.JButton pilih10;
    private javax.swing.JButton pilih11;
    private javax.swing.JButton pilih12;
    private javax.swing.JButton pilih2;
    private javax.swing.JButton pilih3;
    private javax.swing.JButton pilih4;
    private javax.swing.JButton pilih5;
    private javax.swing.JButton pilih6;
    private javax.swing.JButton pilih7;
    private javax.swing.JButton pilih8;
    private javax.swing.JButton pilih9;
    private javax.swing.JLabel studioTxt;
    // End of variables declaration//GEN-END:variables
}
