/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project;

import Class.SetToggleButton;
import Class.User;
import javax.swing.JToggleButton;

/**
 *
 * @author Sulthan Daffa
 */
public class MenuTopUp extends javax.swing.JFrame implements SetToggleButton{

    /**
     * Creates new form MenuTopUp
     */
    private User user;
    private int nominal;
    public MenuTopUp(User user) {
        initComponents();
        this.user = user;
        usernameTxt.setText(user.getUsername());
        setLocationRelativeTo(null);
    }

    private void besarNominal(JToggleButton button){
        String nilai = button.getText();
        nilai = nilai.replace(".", "");
        this.nominal = Integer.parseInt(nilai);
    }
    
    public JToggleButton[] daftarBtn() {
        JToggleButton[] allToggleButtons = {
            pilihan1, pilihan2, pilihan3, pilihan4, pilihan5, pilihan6, pilihan7
        };
        return allToggleButtons;
    }
    
    public void disableButton() {
        for (int i = 0; i < 3; i++) {
            JToggleButton[] buttons = daftarBtn();
            for (JToggleButton button : buttons) {
                button.setSelected(false);
            }
        }
    }
    
    public void pilihButton(JToggleButton button){
        disableButton();
        button.setSelected(true);
        besarNominal(button);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        usernameTxt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pilihan1 = new javax.swing.JToggleButton();
        pilihan2 = new javax.swing.JToggleButton();
        pilihan3 = new javax.swing.JToggleButton();
        pilihan4 = new javax.swing.JToggleButton();
        pilihan5 = new javax.swing.JToggleButton();
        pilihan6 = new javax.swing.JToggleButton();
        pilihan7 = new javax.swing.JToggleButton();
        topUpBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setBackground(new java.awt.Color(54, 48, 98));
        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        jLabel6.setText("Top Up");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        usernameTxt.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        usernameTxt.setText("Username ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(usernameTxt)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(28, 101, 140));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nominal ");

        pilihan1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pilihan1.setText("50.000");
        pilihan1.setMaximumSize(new java.awt.Dimension(76, 23));
        pilihan1.setMinimumSize(new java.awt.Dimension(76, 23));
        pilihan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihan1ActionPerformed(evt);
            }
        });

        pilihan2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pilihan2.setText("100.000");
        pilihan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihan2ActionPerformed(evt);
            }
        });

        pilihan3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pilihan3.setText("150.000");
        pilihan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihan3ActionPerformed(evt);
            }
        });

        pilihan4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pilihan4.setText("200.000");
        pilihan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihan4ActionPerformed(evt);
            }
        });

        pilihan5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pilihan5.setText("250.000");
        pilihan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihan5ActionPerformed(evt);
            }
        });

        pilihan6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pilihan6.setText("300.000");
        pilihan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihan6ActionPerformed(evt);
            }
        });

        pilihan7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pilihan7.setText("500.000");
        pilihan7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihan7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(pilihan5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pilihan6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pilihan7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pilihan1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pilihan2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pilihan3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pilihan4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihan2)
                    .addComponent(pilihan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilihan3)
                    .addComponent(pilihan4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihan7)
                    .addComponent(pilihan6)
                    .addComponent(pilihan5))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        topUpBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        topUpBtn.setForeground(new java.awt.Color(19, 32, 67));
        topUpBtn.setText("Top up");
        topUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topUpBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topUpBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(topUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihan5ActionPerformed
        // TODO add your handling code here:
        pilihButton(pilihan5);
    }//GEN-LAST:event_pilihan5ActionPerformed

    private void pilihan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihan6ActionPerformed
        // TODO add your handling code here:
        pilihButton(pilihan6);
    }//GEN-LAST:event_pilihan6ActionPerformed

    private void pilihan7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihan7ActionPerformed
        // TODO add your handling code here:
        pilihButton(pilihan7);
    }//GEN-LAST:event_pilihan7ActionPerformed

    private void pilihan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihan1ActionPerformed
        // TODO add your handling code here:
        pilihButton(pilihan1);
    }//GEN-LAST:event_pilihan1ActionPerformed

    private void pilihan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihan2ActionPerformed
        // TODO add your handling code here:
        pilihButton(pilihan2);
    }//GEN-LAST:event_pilihan2ActionPerformed

    private void pilihan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihan3ActionPerformed
        // TODO add your handling code here:
        pilihButton(pilihan3);
    }//GEN-LAST:event_pilihan3ActionPerformed

    private void pilihan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihan4ActionPerformed
        // TODO add your handling code here:
        pilihButton(pilihan6);
    }//GEN-LAST:event_pilihan4ActionPerformed

    private void topUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topUpBtnActionPerformed
        // TODO add your handling code here:
        user.tambahSaldo(nominal);
        this.dispose();
    }//GEN-LAST:event_topUpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton pilihan1;
    private javax.swing.JToggleButton pilihan2;
    private javax.swing.JToggleButton pilihan3;
    private javax.swing.JToggleButton pilihan4;
    private javax.swing.JToggleButton pilihan5;
    private javax.swing.JToggleButton pilihan6;
    private javax.swing.JToggleButton pilihan7;
    private javax.swing.JButton topUpBtn;
    private javax.swing.JLabel usernameTxt;
    // End of variables declaration//GEN-END:variables
}
